[tools]
"cargo:git-branch-stash-cli" = "latest"
"cargo:git-stack" = "latest"
go = "1"
node = "24"
pnpm = "10"
python = "3.14"
rust = "1"

[settings]
trusted_config_paths = ["~/ghq/github.com/tapioca24"]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
