# デフォルト: レシピ一覧を表示
default:
    @just -g --list

alias up := update
alias sw := darwin-switch

# すべて更新（flake update → darwin-rebuild → sheldon）
update: nix-update darwin-switch sheldon-update

# nix flake inputs を更新
nix-update:
    sudo nix flake update --flake ~/.config/nix-darwin

# nix-darwin 設定を反映
darwin-switch:
    sudo darwin-rebuild switch --flake ~/.config/nix-darwin

# sheldon プラグインを更新
sheldon-update:
    sheldon lock --update
